name: Documentation
on:
  push:
    branches: ["master"]
    paths: ["docs/**"]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v19.0.1+1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./docs
      
      - name: Execute Discord Webhook
        run: curl -s -L -X POST 'https://discordapp.com/api/webhooks/726465773962265139/${{ secrets.WEBHOOK }}' -H 'Content-Type: application/json' --data-raw '{"embeds": [{"title": "Deployed Documentation to Vercel","description": "https://aerial.now.sh","type": "rich","color": "39169"}]}'
      
      - name: Zip Folder
        run: zip -r deployment docs/
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Deployment
          path: deployment.zip
        
