name: Self Host
on:
  push:
    branches: ["master"]
    paths: ["selfhost/**"]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r selfhost/requirements.txt
      - name: Lint with Flake8
        run: |
          flake8 selfhost/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 selfhost/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Zip Folder
        run: zip -r selfhost selfhost/
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Self Host
          path: selfhost.zip